### ISSUE TITLE
repeatfunc(func,count,*args) - Args is not optional if passing in lambda function, unlike the help suggests - CircuitPython v9-beta1

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_CircuitPython_IterTools#21]
Docstrings suggest repeatfunc(function) will create a generator that can be called infinitely, calling the function each time. This implies the count of repeats is None (default), and the third argument *args is also None. 

This function accepts the 2nd and 3rd arguments as None with argument 1 as a lambda function, but fails if args is not supplied.
This is not the case if passing in a function. Simple test case supplied.

Running on LilyGo T-DisplayS3, but shouldn't matter what board.

```
import adafruit_led_animation.color as color
from adafruit_itertools.adafruit_itertools_extras import *
from adafruit_itertools import *

print(   take(  5, repeatfunc( lambda _: color.YELLOW, None, None )  )   )

def newfunc():
    return color.YELLOW

print(take(5, repeatfunc(newfunc)))

print(take(5, repeatfunc(lambda _: color.YELLOW)))   # crashes here
```

> code.py output:
> [(255, 150, 0), (255, 150, 0), (255, 150, 0), (255, 150, 0), (255, 150, 0)]
> [(255, 150, 0), (255, 150, 0), (255, 150, 0), (255, 150, 0), (255, 150, 0)]
> Traceback (most recent call last):
>   File "code.py", line 12, in <module>
>   File "/lib/adafruit_itertools/adafruit_itertools_extras.py", line 305, in take
>   File "/lib/adafruit_itertools/__init__.py", line 327, in islice
>   File "/lib/adafruit_itertools/__init__.py", line 439, in starmap
> TypeError: function takes 1 positional arguments but 0 were given

**Comment by tyeth** [comment]
muppet, didn't spot the underscore / throw-away argument to lambda, if I change the code to this it works:
```
import adafruit_led_animation.color as color
from adafruit_itertools.adafruit_itertools_extras import *
from adafruit_itertools import *

print(   take(  5, repeatfunc( lambda _: color.YELLOW, None, None )  )   )

def newfunc():
    return color.YELLOW

print(take(5, repeatfunc(newfunc)))

print(take(5, repeatfunc(lambda: color.YELLOW)))
```
